# Use an official lightweight Node.js image as the base image
FROM node:16-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the rest of the application source code into the container
COPY . .

# Expose the port the application will run on
EXPOSE 3001

# Define the command to start the application
CMD ["node", "src/index.js"]
